name: Week 1
on:
  push:
    branches:
      - week1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 2
        if: ${{steps.vars.outputs.count == 1 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/test.helloworld.js

      - name: Step 4
        if: ${{steps.vars.outputs.count == 3 && github.event.head_commit.message != 'Update progress'}}
        env:
          HTTP_ENDPOINT: ${{ secrets.HTTP_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.firstfunction.js

      - name: Step 5
        if: ${{steps.vars.outputs.count == 4 && github.event.head_commit.message != 'Update progress'}}
        env:
          FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
        run: |
          node .bit/tests/test.secret1.js

